apiVersion: v1
data:
  mq01.mqsc: "DEFINE QLOCAL(IBM.THIS.QUEUE.FOR.YOU) REPLACE \nDEFINE QLOCAL(IBM.DEMO.Q)
    BOQNAME(IBM.DEMO.Q.BOQ) BOTHRESH(3) REPLACE\nDEFINE QLOCAL(IBM.DEMO.Q.BOQ) REPLACE\n*
    Use a different dead letter queue, for undeliverable messages\nDEFINE QLOCAL('DEV.DEAD.LETTER.QUEUE')
    REPLACE\nALTER QMGR DEADQ('DEV.DEAD.LETTER.QUEUE')\nDEFINE CHANNEL('IBM.APP.SVRCONN')
    CHLTYPE(SVRCONN)\nALTER QMGR CHLAUTH (DISABLED)\n* DEFINE CHANNEL('MONITORING_CHL')
    CHLTYPE(SVRCONN)\n* SET CHLAUTH(MONITORING_CHL) TYPE(BLOCKUSER) USERLIST(NOBODY)\nREFRESH
    SECURITY TYPE(CONNAUTH)\n* optional\nDEFINE SERVICE(APPLY_MQSC) CONTROL(QMGR)
    SERVTYPE(SERVER) STARTCMD('/mq-config/start-mqsc.sh') STARTARG(QM1) STOPCMD('/mq-config/start-mqsc.sh')
    STOPARG('') STDOUT('') STDERR('')\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mq01-mqsc
  namespace: mq01-dev
